import "~/styles/globals.css";

import { Inter } from "next/font/google";
import Link from "next/link";
import { Toaster } from "~/components/ui/sonner";
import { ClerkProvider, SignedIn, UserButton } from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable} dark`}>
          <main className="flex min-h-screen flex-col">
            <header className="flex items-center justify-between border-b border-slate-600 p-4">
              <Link href="/">
                <span>Logo</span>
              </Link>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </header>
            <div className="flex flex-grow">
              <div className="flex w-64 flex-col gap-4 border-r border-slate-600 p-4">
                <Link href="/tts">Text to Speach</Link>
                <Link href="/stt">Speach to Text</Link>
                <Link href="/tti">Text to Image</Link>
              </div>
              <div className="w-full">
                <div className="w-full p-4">{children}</div>
              </div>
            </div>
          </main>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
